### ISSUE TITLE
Websocket chokes on refused connection

### ISSUE THREAD

**Issue by timokoch** [VirtualProgrammingLab/viplab-websocket-api#13]
I'm running a viplab front end locally, setting up the necessary services with the following docker-compose setup:

```
version: "3"

services:
  activemq:
    image: viplab-artemis:2.11.0
    build:
      context: ./artemis
      args:
        ACTIVEMQ_ARTEMIS_VERSION: "2.11.0"
    ports:
      - 8084:8161
      - 5672:5672
    environment:
      ARTEMIS_USERNAME: user
      ARTEMIS_PASSWORD: password
  websocket-api:
    build: ./websocket-api
    ports:
      - 8083:8080
    environment:
      JWKS_FILE: /config/jwks.json
    volumes:
      - ./jwks.json:/config/jwks.json:ro
    depends_on:
      - activemq
  standalone-frontend:
    image: viplab/standalone-frontend:latest
    ports:
      - 8085:5000
    volumes:
      - ./jwks.private.json:/jwks.private.json:ro
      - ./examples:/input:ro
```

Sometimes the services start-up fine and sometimes the websocket fails to connect to activemq and dies with an error: `java.net.ConnectException: Connection refused`. I assume the activemq is not ready yet in these cases. I attached the startup log:

[startup.log](https://github.com/VirtualProgrammingLab/viplab-websocket-api/files/4614491/startup.log)

__Observed behaviour__:
The websocket dies.

__Expected behaviour__:
The websocket tries again later to establish the connection.
